version: '3.8'

x-services-volume:
  &services-volume
  type: bind
  source: .
  target: /usr/src/app

services:
  # analysis env
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    #entrypoint: Xvfb :1 -screen 0 1024x768x24 &
    volumes: 
      - *services-volume
    #  - .:/usr/src/app
    environment:
      - DISPLAY=:1
    ports:
      - 8888:8888
    command: poetry run poe jn 
  # navigate to: http://localhost:9090/zap/
  zap: 
    image: owasp/zap2docker-weekly
    volumes: 
      - <<: *services-volume
        target: /appdata
    ports:
      - 9090:8080
      - 9100:8090
    user: zap
    stdin_open: true
    command: zap-webswing.sh
  # dvwa: 
  #   image: vulnerables/web-dvwa
  #   ports:
  #     - 9990:80
  # webgoat: 
  #   image: webgoat/webgoat
  #   ports:
  #     - 9991:8080
  #     - 9090:9090
  #   environment:
  #     - TZ=Europe/Amsterdam
  # https://github.com/webpwnized/mutillidae-docker/blob/master/docker-compose.yml
  #mutillidae:
  # ...
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - 9993:3000
  # splash server to scrape dynamic pages
  # splash:
  #     restart: "no" # Options: on-failure, unless-stopped, always
  #     # assign the built image a name(:tag)
  #     image: scrapinghub/splash
  #     ports:
  #         # splash service
  #         - "8050:8050"